# -*- coding: utf-8 -*-
"""translate_msa_to_arabizi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1guZao6TQMFYgqlyZHdtQmCieObwwC5kZ

# Convert Arabic Boundary-Set to Arabizi with OpenRouter

This notebook loads the Arabic boundary-set from CSV or JSON, converts the `Prompt` column to Arabizi using `openai/gpt-4o-mini` through OpenRouter, and saves the converted dataset in both CSV and JSON formats.

## What this notebook does

- Reads the input dataset from `.csv` and `.json`
- Preserves the original columns: `Safe/Unsafe`, `Category`, `Prompt`
- Replaces the Arabic `Prompt` text with an Arabizi version
- Writes a converted `.csv` and `.json` with the same schema
"""

!pip -q install openai pandas tqdm

import json
import time
from pathlib import Path

import pandas as pd
from openai import OpenAI
from tqdm.auto import tqdm

OPENROUTER_API_KEY = "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" # Replace with your actual API key
MODEL_NAME = "openai/gpt-4o-mini"

INPUT_CSV_PATH = "/content/Arabic boundary-set.csv"
INPUT_JSON_PATH = "/content/Arabic boundary-set.json"
OUTPUT_CSV_PATH = "/content/Arabic boundary-set-arabizi.csv"
OUTPUT_JSON_PATH = "/content/Arabic boundary-set-arabizi.json"

REQUEST_DELAY_SECONDS = 0.4
MAX_RETRIES = 3

client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=OPENROUTER_API_KEY,
)

SYSTEM_PROMPT = '''Only convert Arabic text into Arabizi.
Do not answer the prompts. Do not analyse meaning.
Return only the Arabizi version of the input text.
Preserve the original meaning exactly.
Do not translate to English.
Do not summarize or explain.
Keep punctuation and formatting when possible, especially quotations.'''

def to_arabizi(text: str) -> str:
    last_error = None
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            response = client.chat.completions.create(
                model=MODEL_NAME,
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": text},
                ],
                temperature=0,
            )
            return response.choices[0].message.content.strip()
        except Exception as exc:
            last_error = exc
            if attempt == MAX_RETRIES:
                raise
            time.sleep(2 * attempt)
    raise last_error

csv_path = Path(INPUT_CSV_PATH)
json_path = Path(INPUT_JSON_PATH)

if not csv_path.exists():
    raise FileNotFoundError(f"CSV file not found: {csv_path}")
if not json_path.exists():
    raise FileNotFoundError(f"JSON file not found: {json_path}")

df = pd.read_csv(csv_path)
with json_path.open('r', encoding='utf-8') as f:
    json_rows = json.load(f)

required_columns = ['Safe/Unsafe', 'Category', 'Prompt']
missing = [col for col in required_columns if col not in df.columns]
if missing:
    raise ValueError(f"CSV is missing required columns: {missing}")

if not isinstance(json_rows, list):
    raise ValueError('JSON input must be a top-level array.')

print(f"Loaded CSV rows: {len(df)}")
print(f"Loaded JSON rows: {len(json_rows)}")

converted_prompts = []
for prompt in tqdm(df['Prompt'].fillna('')):
    if not str(prompt).strip():
        converted_prompts.append('')
        continue
    converted_prompts.append(to_arabizi(str(prompt)))
    time.sleep(REQUEST_DELAY_SECONDS)

converted_df = df.copy()
converted_df['Prompt'] = converted_prompts

converted_json_rows = []
for row, arabizi_prompt in zip(json_rows, converted_prompts):
    new_row = dict(row)
    new_row['Prompt'] = arabizi_prompt
    converted_json_rows.append(new_row)

print(f"Converted {len(converted_prompts)} prompts")

converted_df.to_csv(OUTPUT_CSV_PATH, index=False, encoding='utf-8-sig')
with open(OUTPUT_JSON_PATH, 'w', encoding='utf-8') as f:
    json.dump(converted_json_rows, f, ensure_ascii=False, indent=2)

print(f"Saved CSV to {OUTPUT_CSV_PATH}")
print(f"Saved JSON to {OUTPUT_JSON_PATH}")
converted_df.head(3)